### ISSUE TITLE
Use the package.dhall convention

### ISSUE THREAD

**Issue by mx00s** [bgamari/dhall-gitlab-ci#1]
Unlike `Text`, Dhall's URL imports do not support any kind of interpolation. Consequently, updating expressions like [this](https://gitlab.com/mx00s/dhall-gitlab-pipeline/-/blob/cb343b75117cdd6a691bc97e152a28bb6fd72573/.gitlab-ci.dhall) to use more recent revisions is awkward. I'd have to edit the git revision in multiple URL imports.

Several Dhall projects use a `package.dhall` file so users can make a `let` binding to its URL and access all the project's public features through it. Here is the [`package.dhall`](https://github.com/dhall-lang/dhall-kubernetes/blob/master/package.dhall) for `dhall-kubernetes`.

### Potential Alternatives?

I considered whether other Dhall features could simplify maintenance in my project without asking for a `package.dhall` here, but haven't found any. These issues and comments in `dhall-lang`  offer some useful context.

* https://github.com/dhall-lang/dhall-lang/issues/219
* https://github.com/dhall-lang/dhall-lang/issues/139#issuecomment-417953563

The [comment following that last one](https://github.com/dhall-lang/dhall-lang/issues/139#issuecomment-420269275) about expanding the type hierarchy might be relevant to this concern, but I don't see it yet.

**Comment by bgamari** [comment]
I would happily accept a pull request.
